### ISSUE TITLE
老板,怎么不往下更新了,还等着呢

### ISSUE THREAD

**Issue by jackey-jiang** [zhaodongxx/spring-boot2-shiro-project#1]
写的很清晰明了,适合我这种入门shiro的,还望老板坚持下去,把shiro篇写完咯

**Comment by zhaodongxx** [comment]
@jackey-jiang 谢谢你的支持，我已经更新了新的一篇，非常的详细而又啰嗦。希望不会让你失望

**Comment by jackey-jiang** [comment]
@zhaodongxx 谢谢老板,老板大气,希望能够把shiro篇整完
